### ISSUE TITLE
Setting config.js file.

### ISSUE THREAD

**Issue by ab99484** [natterstefan/react-trello-multiboard#21]
Hi @natterstefan 
I have copied config.example.js to config.example.js. Then I have set api_key and company_name.
```
module.exports = {
  app_title: 'Management Trello',
  api_key: 'ab1c9acd0cba2da8xxxxx...xxx',
  google_analytics_property: 'UA-12345678-9',
  company_member: 'Oleg',
  preferred_members: /exampleusername|anotheruser/,
  lists: [/#upcoming/],
  boards: [
    {
      shortcut: 'hw',
      name: 'hello-world',
      id: 'board-1', // optional: only required when board is public but user should see it
      estimates_with_round_brackets: true,
      estimates_with_square_brackets: true,
    },
  ],
}
``` 

But I have some errors.
Please check the config file and let me know what I am wrong.
Regards

**Comment by ab99484** [comment]
So I hope you to provide a sample config file for the test.
Thank you.

**Comment by natterstefan** [comment]
Hi @rufoot,

thanks for your interesting in using RTM. Let me try to help you. Have you seen the [Config.js section](https://github.com/natterstefan/react-trello-multiboard#configjs) in the Readme already?

The example you copied still contains some example values (mainly used for testing). Please, see my notes right next to the value with the questions/hints for you.

```js
module.exports = {
  app_title: 'Management Trello',
  api_key: 'ab1c9acd0cba2da8xxxxx...xxx',
  google_analytics_property: 'UA-12345678-9',
  company_member: 'Oleg',
  preferred_members: /exampleusername|anotheruser/, // I would suggest changing this to `Oleg` as well then
  lists: [/#upcoming/], // do your lists contain #upcoming in their name?
  boards: [
    {
      shortcut: 'hw', // name you want to display on the dashboard
      name: 'hello-world', // slug of the trello board, eg. https://trello.com/b/asdf23f/rocket-dev ==> 'rocket-dev'
      id: 'board-1', // optional: only required when board is public and your user is not part of it
      estimates_with_round_brackets: true,
      estimates_with_square_brackets: true,
    },
  ],
}
```

Can you share the error you get with me, please?

**Comment by ab99484** [comment]
Thanks for your response.
I have fixed this issue with `id = 0`.

I have another one question. If I use .obj file, Can I change material of the model?
For example "color", "text", "shape"...

I'd like you to explain more detail about this. Thank you.

**Comment by natterstefan** [comment]
Hi @rufoot,

that is correct. `id = 0` has the same effect as if you remove it (because it is optional, and only required if the board is public and users might be not a member of the public board).

Regarding the material-ui design: Currently, it is not possible to change colors, font-size and others.

But that could most likely be of value, I'll think about it and how to integrate it. Thanks for asking.

**Comment by natterstefan** [comment]
Hi @rufoot, I am gonna close this issue now and track the UI customizations in another one: #22.
