### ISSUE TITLE
Trello responds with "Invalid return_url" when trying to authorize token

### ISSUE THREAD

**Issue by goljavi** [natterstefan/react-trello-multiboard#23]
## Question
Hi, i wanted to know if i'm doing something wrong. When i execute the app, trello responds with "Invalid return_url" 

## Relevant information
These are the steps i've taken:
- Cloned the repo
- Executed yarn command
- Went to https://trello.com/app-key and copied the key
- Pasted it into the config.js file along with the rest of the information.
- Went to allowed origins and put localhost:2222
- Went to localhost:2222, this redirects me to https://trello.com/1/authorize?... 
- Received a message from trello telling me "Invalid return_url"

### Your Environment

* Browser: Chrome
* Browser version: 78
* OS: Windows 10 x64
* App Version: 0.2.1

**Comment by natterstefan** [comment]
Hi @goljavi,

first of all: I am sorry, must have missed the notification.

Now back to your problem: does it still exist? Have you tried it with `localhost` instead of `localhost:2222` as ["allowed origin" on trello](https://trello.com/app-key)?

**Comment by goljavi** [comment]
Thank you for your answer!
Yes, the problem still exists. I have tried with `localhost` and `localhost:2222`
![image](https://user-images.githubusercontent.com/18222755/70249377-14675300-175b-11ea-84f7-bf2be16bdb0a.png)

Also, this is the url it redirects me to: https://trello.com/1/authorize?response_type=token&key=xxxx&redirect_uri=http%3A%2F%2Flocalhost%3A2222%2F%23%2F&callback_method=fragment&scope=read&expiration=never&name=EGLC+Multiboard

-----

**Edit: I removed the images, as they included your key.**

**Comment by natterstefan** [comment]
Hi @goljavi,

finally I had time to test it by myself. It still works for me. Not sure if the port is required, but these are my "Current Origins" settings:

![image](https://user-images.githubusercontent.com/1043668/72165454-d0a1e200-33c7-11ea-93d4-26b71ee8b10e.png)

I assume the https is the issue, your localhost is not served via https, isn't it?

Can you verify that this works?

**Comment by goljavi** [comment]
Hey Stefan!
I was setting an https:// origin when it was supposed to be http://
It was a Trello bug, because it automatically appendend https:// even if you wrote an url beggining with http://
Now it is fixed and everything works fine!
Thanks!

**Comment by natterstefan** [comment]
Perfect! Happy to hear it works for you now @goljavi.

**Comment by JoseChavez98** [comment]
Hi! I'm working locally in ubuntu, using firefox. I'm running a simple .html file with client.js. What should I put on the origin field?
