### ISSUE TITLE
Trello responds with "Invalid return_url" when trying to authorize token 

### ISSUE THREAD

**Issue by JoseChavez98** [natterstefan/react-trello-multiboard#24]
Hi! I'm really sorry for opening an issue for this, but I'm having a really rough time with this.

I'm using client.js in a simple .html file. Can you help me to see why I'm getting this error? 
Also, I've been investigating and It's probably because of Allowed Origins, but I  don't know what to put as my origin :(. I've tried with  
http://localhost
https://localhost
http://localhost:222
https://localhost:2222
http://localhost:3000
https://localhost:3000

### Your Environment

* Browser: Firefox
* Browser version: 76.0.1
* OS: Ubuntu 20.04
* App Version: index.html

**Comment by natterstefan** [comment]
Hi @JoseChavez98,

don't worry. I'm happy to help you - if I can. Have you seen my comment on the other issue: https://github.com/natterstefan/react-trello-multiboard/issues/23#issuecomment-573086608.

The following values are set on https://trello.com/app-key (in my setup):

- `http://localhost`
- `http://localhost:2222`

From the list you posted, I see there are two typos:

> http://localhost:222
> localhost:2222

- `http://localhost:222` --> is missing another `2`
- `localhost:2222` --> is missing `http://`

Can you test if changing your values similar to mine resolves your issue, please?

**Comment by JoseChavez98** [comment]
Hi! This is awkward , but just because I was writing fast I made those mistakes.  
Yes, I've tried with all the correct origins without success.  
I have been investigating on which origin does firefox use and they say is the localhost:80 , but this also  doesn't work.
If you can help me , I will be really happy. 
Thank you

**Comment by natterstefan** [comment]
🤔 Let's see.

Can you tell me more about this, please?

> I'm using client.js in a simple .html file. Can you help me to see why I'm getting this error?

So you are not using the app as-is, but only the created *.js file on another index.html page?

**Comment by natterstefan** [comment]
Hi @JoseChavez98, were you able to resolve this issue?
